org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.21
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.08.20-1.20.1

mod_id=tacz_extras
mod_name=TACZ Extras
mod_version=1.1.0
mod_group_id=io.github.thefakedevs.taczextras
mod_authors=TheFakeDevs
mod_display_url=https://github.com/thefakedevs
mod_license=All-Rights-Reserved
mod_description=Configurable runtime patches and quality-of-life extras for TACZ.

tacz_version=1.1.6-svocraft-e0d0c29f
tacz_local_version=1.1.6-svocraft-20d798dc
tacz_local_jar=../TACZ/build/libs/tacz-1.20.1-1.1.6-svocraft-20d798dc.jar
